### ISSUE TITLE
56 style errors when building project in Flutter 2.5.1

### ISSUE THREAD

**Issue by CarltonBranch** [Project-Easter/Flutter-UI#113] opened 2021-10-04 02:58 UTC
## Description
There are 56 style errors when building in latest Flutter

## Screenshots
Upload the current working screenshots here.
![Screenshot_1](https://user-images.githubusercontent.com/17789035/135786681-beac7376-51a6-4b6c-9393-9f3cfeb18d7f.png)
![Screenshot_2](https://user-images.githubusercontent.com/17789035/135786820-fe7fa7c7-b87c-4833-a4df-8018d1ca9c37.png)

## Steps to Reproduce
Please provide detailed steps for reproducing the issue.

1. Update Flutter
3. Check errors

## Additional data
I would like to update the app and submit a PR

**Comment by Mohitmadhav** [comment] 2021-10-04 03:01
@CarltonBranch , it's the duplicate of #99

**Closed** 2021-10-04 04:30 UTC
Labels: duplicate
